CREATE TYPE "gender_type" AS ENUM (
  'M',
  'F'
);

CREATE TYPE "intent_type" AS ENUM (
  'serieux',
  'decouverte',
  'fun'
);

CREATE TYPE "interaction_type" AS ENUM (
  'like',
  'dislike',
  'superlike'
);

CREATE TYPE "transaction_status" AS ENUM (
  'pending',
  'success',
  'failed'
);

CREATE TYPE "report_status" AS ENUM (
  'pending',
  'resolved',
  'dismissed'
);

CREATE TYPE "admin_role" AS ENUM (
  'admin',
  'moderator'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE,
  "password_hash" text,
  "gender" gender_type,
  "birthdate" date,
  "city" varchar,
  "location" geography,
  "intent" intent_type,
  "is_verified" boolean DEFAULT false,
  "is_ghost_mode" boolean DEFAULT false,
  "fcm_token" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "photos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "url" text,
  "is_primary" boolean DEFAULT false,
  "is_verification_selfie" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "passions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar UNIQUE
);

CREATE TABLE "user_passions" (
  "user_id" integer,
  "passion_id" integer,
  PRIMARY KEY ("user_id", "passion_id")
);

CREATE TABLE "swipes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" integer,
  "receiver_id" integer,
  "type" interaction_type,
  "is_match" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" integer,
  "receiver_id" integer,
  "content" text,
  "media_url" text,
  "read_at" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "wallets" (
  "user_id" integer PRIMARY KEY,
  "balance" integer DEFAULT 0
);

CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "kkiapay_ref" varchar UNIQUE,
  "amount" integer,
  "credits_added" integer,
  "status" transaction_status DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "subscriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "type" varchar DEFAULT 'ghost_mode',
  "starts_at" timestamp DEFAULT (now()),
  "ends_at" timestamp,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporter_id" integer,
  "reported_id" integer,
  "reason" text,
  "status" report_status DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "admins" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE,
  "password_hash" text,
  "role" admin_role DEFAULT 'moderator',
  "last_login" timestamp
);

ALTER TABLE "photos" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_passions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_passions" ADD FOREIGN KEY ("passion_id") REFERENCES "passions" ("id");

ALTER TABLE "swipes" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "swipes" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "wallets" ("user_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "subscriptions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reports" ADD FOREIGN KEY ("reporter_id") REFERENCES "users" ("id");

ALTER TABLE "reports" ADD FOREIGN KEY ("reported_id") REFERENCES "users" ("id");
